development:
  adapter: postgresql
  encoding: unicode
  database: reddit_development
  pool: 5
  username: appacademy
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: reddit_test
  pool: 5
  username: appacademy
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: reddit_production
  pool: 5
  username: reddit
  password:
